name: Example

on:
  pull_request:
    types: [labeled]

jobs:
  example:
    runs-on: [self-hosted, linux, X64, truex-dev, us-east-1]
    steps:
      - name: example
        run: echo "hello world"
